nginx:
  container_name: nginx
  image: nginx
  ports:
    - "80:80"
  volumes:
    # Nginx configuration
    - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
  links:
    - django
django:
  container_name: django
  build: .
  ports:
    - "32771:8000"
  volumes:
    # Django app
    - ./app:/app